import json
import os

experiment_table_name = "video_validation_experiment"
example_table_name = "example_videos"

ROOT_DIR = "/home/tim/work/su-thesis-project/video-validation-back-end"

valences = ["pos", "neg"]

emotion_abr_to_emotion_id = {
  "reg": 0,
  "conf": 1,
  "det": 2,
  "dou": 3,
  "env": 4,
  "adm": 5,
  "sad": 6,
  "gra": 7,
  "ele": 8,
  "pos_sur": 9,
  "fea": 10,
  "neg_sur": 11,
  "ang": 12,
  "amu": 13,
  "rej": 14,
  "scha": 15,
  "sat": 16,
  "dist": 17,
  "awe": 18,
  "ins": 19,
  "tri": 20,
  "hop": 21,
  "neu": 22,
  "ple": 23,
  "sex": 24,
  "pea": 25,
  "bor": 26,
  "conc": 27,
  "ten": 28,
  "int": 29,
  "nos": 30,
  "sar": 31,
  "cont": 32,
  "hap": 33,
  "anx": 34,
  "disg": 35,
  "exc": 36,
  "disa": 37,
  "rel": 38,
  "emb": 39,
  "gui": 40,
  "pri": 41,
  "mov": 42,
  "sha": 43
}

emotion_id_to_emotion_abr = dict(zip(emotion_abr_to_emotion_id.values(), emotion_abr_to_emotion_id.keys()))

emotion_id_to_valence = {
    0: "neg",
    1: "neg",
    2: "pos",
    3: "neg",
    4: "neg",
    5: "pos",
    6: "neg",
    7: "pos",
    8: "pos",
    9: "pos",
    10: "neg",
    11: "neg",
    12: "neg",
    13: "pos",
    14: "neg",
    15: "neg",
    16: "pos",
    17: "neg",
    18: "pos",
    19: "pos",
    20: "pos",
    21: "pos",
    22: "neu",
    23: "pos",
    24: "pos",
    25: "pos",
    26: "neg",
    27: "pos",
    28: "pos",
    29: "pos",
    30: "neg",
    31: "neg",
    32: "neg",
    33: "pos",
    34: "neg",
    35: "neg",
    36: "pos",
    37: "neg",
    38: "pos",
    39: "neg",
    40: "neg",
    41: "pos",
    42: "pos",
    43: "neg"
}

video_files = [
    # female naro
    {"video_id": "A91",
     "sex": "female",
     "prosody": "naro"},
    {"video_id": "A102",
     "sex": "female",
     "prosody": "naro"},
    {"video_id": "A205",
     "sex": "female",
     "prosody": "naro"},
    {"video_id": "A221",
     "sex": "female",
     "prosody": "naro"},
    {"video_id": "A227",
     "sex": "female",
     "prosody": "naro"},
    {"video_id": "A425",
     "sex": "female",
     "prosody": "naro"},
    {"video_id": "A426",
     "sex": "female",
     "prosody": "naro"},

    # female meli
    {"video_id": "A323",
     "sex": "female",
     "prosody": "meli"},
    {"video_id": "A332",
     "sex": "female",
     "prosody": "meli"},
    {"video_id": "A334",
     "sex": "female",
     "prosody": "meli"},
    {"video_id": "A337",
     "sex": "female",
     "prosody": "meli"},
    {"video_id": "A405",
     "sex": "female",
     "prosody": "meli"},
    {"video_id": "A407",
     "sex": "female",
     "prosody": "meli"},
    {"video_id": "A424",
     "sex": "female",
     "prosody": "meli"},

    # male naro
    {"video_id": "A200",
     "sex": "male",
     "prosody": "naro"},
    {"video_id": "A207",
     "sex": "male",
     "prosody": "naro"},
    {"video_id": "A220",
     "sex": "male",
     "prosody": "naro"},
    {"video_id": "A72",
     "sex": "male",
     "prosody": "naro"},
    {"video_id": "A438",
     "sex": "male",
     "prosody": "naro"},
    {"video_id": "A435",
     "sex": "male",
     "prosody": "naro"},
    {"video_id": "A437",
     "sex": "male",
     "prosody": "naro"},

    # male meli
    {"video_id": "A303",
     "sex": "male",
     "prosody": "meli"},
    {"video_id": "A327",
     "sex": "male",
     "prosody": "meli"},
    {"video_id": "A55",
     "sex": "male",
     "prosody": "meli"},
    {"video_id": "A64",
     "sex": "male",
     "prosody": "meli"},
    {"video_id": "A67",
     "sex": "male",
     "prosody": "meli"},
    {"video_id": "A410",
     "sex": "male",
     "prosody": "meli"},
    {"video_id": "A417",
     "sex": "male",
     "prosody": "meli"},
]


sex_dict = {d['video_id']: d['sex'] for d in video_files}
prosody_dict = {d['video_id']: d['prosody'] for d in video_files}


video_ids = [
    'A91',
    'A102',
    'A205',
    'A221',
    'A227',
    'A425',
    'A426',
    'A323',
    'A332',
    'A334',
    'A337',
    'A405',
    'A407',
    'A424',
    'A200',
    'A207',
    'A220',
    'A72',
    'A438',
    'A435',
    'A437',
    'A303',
    'A327',
    'A55',
    'A64',
    'A67',
    'A410',
    'A417'
]

emotion_id_to_emotion = {
    '2': 'Beslutsamhet',
    '5': 'Beundran',
    '7': 'Tacksamhet',
    '8': 'Upphöjdhet',
    '9': 'Positiv förvåning',
    '13': 'Nöje',
    '16': 'Tillfredsställelse/Belåtenhet',
    '18': 'Vördnad',
    '19': 'Inspiration',
    '20': 'Triumf/Prestation',
    '21': 'Hopp',
    '22': 'Neutral',
    '23': 'Sinnlig njutning',
    '24': 'Sexuell lust',
    '25': 'Lugn/Frid',
    '27': 'Koncentration',
    '28': 'Ömsinthet',
    '29': 'Intresse/Nyfikenhet',
    '33': 'Glädje',
    '36': 'Exalterad/Förväntansfull',
    '38': 'Lättnad',
    '41': 'Stolthet',
    '42': 'Att bli rörd',
    '0': 'Ånger',
    '1': 'Förvirring',
    '3': 'Tvivel',
    '4': 'Avund',
    '6': 'Sorg',
    '10': 'Rädsla',
    '11': 'Negativ förvåning',
    '12': 'Ilska',
    '14': 'Att bli avvisad',
    '15': 'Skadeglädje',
    '17': 'Nöd/Smärta',
    '26': 'Uttråkad',
    '30': 'Nostalgi',
    '31': 'Sarkasm',
    '32': 'Förakt',
    '34': 'Oro/Ängslan',
    '35': 'Äckel',
    '37': 'Besvikelse',
    '39': 'Genans',
    '40': 'Skuld',
    '43': 'Skam'
}
